services:
  fastapi:
    build: .
    image: fastapi-server-image:latest
    container_name: fastapi-server-container
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - METRIC_COLLECTION_INTERVAL=5
    networks:
      - fastapi-metrics-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - fastapi-metrics-net

networks:
  fastapi-metrics-net:
